Add encryption pass
Hari-Nagarajan/fairgame pull request #431
Opened 2020-12-18 21:16 UTC by MrTpat

Adds command line argument --encryption-pass for people that may want to not have to do the login manually. Useful for people who may want to schedule jobs using the script and not having to enter the password through a stdin pipe.

Usage:

`python app.py amazon --encryption-pass <password>`

2020-12-18 21:22 UTC, DakkJaniels commented
Not sure we want to implement this in repo, as it defeats the purpose of putting in credential encryption, but let's see what others think.

2020-12-18 21:25 UTC, MrTpat commented
My main use case was earlier for me it kept crashing for some reason, got annoying having to input the password each time. It does lax the security principle a bit, I will agree.

2020-12-18 21:33 UTC, unapproachable commented
How do we feel about an option that uses a 'known' password that's in the code itself  so the password is at least encrypted in the file to prevent plaintext passwords being stored.  If someone stores it with the default password, they've accepted that no one will ever get their file and they'll never post it in the wild, since it could be easily decrypted.  I'm okay with having an option that bypasses asking for the passphrase, but I sincerely don't believe we want to be the reason people put their Amazon details into a plain text file.  Could that be included in this so that if you spawn it with that option and no credential file exists, it does a known password and then the flag is needed for all future runs?  And we could make it something like --low-security so you always run it in "low-security" mode and only brave souls run it that way?

2020-12-18 21:37 UTC, MrTpat commented
> How do we feel about an option that uses a 'known' password that's in the code itself so the password is at least encrypted in the file to prevent plaintext passwords being stored. If someone stores it with the default password, they've accepted that no one will ever get their file and they'll never post it in the wild, since it could be easily decrypted. I'm okay with having an option that bypasses asking for the passphrase, but I sincerely don't believe we want to be the reason people put their Amazon details into a plain text file. Could that be included in this so that if you spawn it with that option and no credential file exists, it does a known password and then the flag is needed for all future runs? And we could make it something like --low-security so you always run it in "low-security" mode and only brave souls run it that way?

Im a bit confused as to what your saying, I didnt in this PR store any plaintext passwords. Its simply a command line option where you pass in the passwordtext itself. I suppose the only place where it would actually be stored is in your bash history.

2020-12-18 21:42 UTC, DakkJaniels commented
I think that was referring to how things were originally. If you put this in the .bat file, you'd be storing the key in plain text though

2020-12-18 21:45 UTC, MrTpat commented
> I think that was referring to how things were originally. If you put this in the .bat file, you'd be storing the key in plain text though

Agreed, I dont think we necessary should put this in the bat file. The plaintext password hypothetically would not be stored anywhere if we do not include it in the bat file. Its simply an optional argument that I think people would find helpful to use for specific use cases. Most people should continue using the script as is (without using the argument), but I think this could be added in just as a convenience thing, after making sure people understand the potential risks of passing in passwords like this. I was originally inspired by openVPNs command line flag -p that does the same thing.

2020-12-19 00:10 UTC, SalvadorSTM commented
I support this feature. Especially for crashes as stated above. Passwords are cached in the browser anyways so typing the decryption key in every time becomes redundant. Users should only ever have to login once (on the first run) until their cached passwords expire.

2020-12-22 16:23 UTC, DakkJaniels requested changes
Can you fix so it can merge in cleanly, and just change the flag to --p

2020-12-23 14:16 UTC, DakkJaniels approved these changes

2020-12-23 14:16 UTC, DakkJaniels commented
I think the wrong variable was still listed - updated to "p" - will pull in now.

2020-12-23 14:17 UTC, merged