Add python3-pip repo in sources list
Hari-Nagarajan/fairgame pull request #602
Opened 2021-03-23 09:28 UTC by SlimShadys

- It has been tested on a fresh VM with Ubuntu 20.10 that just running the python3-pip installation gives such error: 'E: Package 'python3-pip' has no installation candidate'
  So we add the proper repo, before running the installation process.

Signed-off-by: Gianmarco Scarano <gianmarcoscarano@gmail.com>

2021-04-01 13:24 UTC, JordyUSA submitted a review, later dismissed

2021-04-26 18:13 UTC, timbru31 requested changes

2021-04-26 18:13 UTC, timbru31 commented on README.md
> +`sudo add-apt-repository universe && sudo apt-get update`
```suggestion
Add Universe repo (this might be optional depending on your distro):
`sudo add-apt-repository universe && sudo apt update`
```

2021-04-26 18:17 UTC, DakkJaniels approved these changes
I don't run linux, so I assume this is accurate.

2021-04-26 18:17 UTC, merged